name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
      description: Version of the node
      default: 20.x
      required: false
  working-directory:
      description: Working directory
      default: .
      required: false

runs: 
  using: composite
  steps:
    - name: Setup node version ${{inputs.node-version}}
      uses: actions/setup-node@V3
      with: 
        node-version: ${{inputs.node-version}}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
          path: ${{inputs.working-directory}}/node-modules
          key: node_modules-${{hashfiles('${{working-directory}}/package-lock.json')}}
    - name: Install Dependencies
      if: ${{steps.cache.output.cache-hit != true}}
      run: npm ci
      shell: bash
      working-directory: ${{working-directory}}


