name: Second Workflow
on: push
env:
    MY_VAR: Goldy
jobs:
    echoqa:
        runs-on: ubuntu-latest
        steps:
            - name: BBB
              id:   BBB
              run: |
                echo ${{github.ref}}
                echo ${{github.action}}
                echo ${{github.action_path}}
                echo ${{github.actor}}
                echo ${{github.event}}
                echo ${{github.event_name}}
                echo ${{github.path}}
                echo ${{github.ref_name}}
                echo ${{github.repository}}
                echo ${{github.repository_owner}}
                echo ${{github.server_url}}
            - name: AAA
              id:   AAA
              run: |
                echo ${{vars.MY_VAR}}
                echo ${{env.MY_VAR}}
               



 

