name: Second Workflow
on: push
jobs:
    echoqa:
        runs-on: ubuntu-latest
        steps:
            - name: BBB
              id:   BBB
              run: echo ${{github.sha}}
            - name: AAA
              id:   AAA
              run: echo 'AAA'



 

